name: Krahn Capital
favicon: null
layout_spectrum: 0.12998579861596227
typography_spectrum: 0.6253676898777485
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefebe'
    - '#febb28'
    - '#4d2700'
    - '#a48d63'
    - '#754a06'
  brandStrength: 1
  lightness: 0.44991812389343977
  saturation: 0.9011791360098869
  rhythmicContrast: 0.19765088031999767
purpose: []
